Day11/Prashant/HighwayHelp/Models/ErrorViewModel.cs
namespace HighwayHelp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Day11/Prashant/HighwayHelp/Controllers/AuthController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HighwayHelp.Models;
using BLL;
using BOL;
using System.Collections.Generic;

namespace HighwayHelp.Controllers;

public class AuthController : Controller
{
    private readonly ILogger<AuthController> _logger;

    public AuthController(ILogger<AuthController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        // HelpManager hm=new HelpManager();
        // List<Hospital> allHospitals=hm.GetAllHospitals();
        // this.ViewData["hospitals"]=allHospitals;

        return View();
    }

    public IActionResult Login()
    {
        // HelpManager hm=new HelpManager();
        // List<Hospital> allHospitals=hm.GetAllHospitals();
        // this.ViewData["hospitals"]=allHospitals;

        return View();
    }

    public IActionResult WelcomeAdmin()
    {
        return View();
    }

    public IActionResult Validate(string username,string password)
    {
        // Console.WriteLine("inside controllers Deatils");
        //  HelpManager hm=new HelpManager();
        //  Hospital hospital=hm.GetHospital(id);
        //  this.ViewData["hospital"]=hospital;
        HelpManager hm=new HelpManager();
        if(hm.DoValidate(username,password))
        {

            return Redirect("WelcomeAdmin");
        }
         return View();

    } 

   

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Day11/Prashant/HighwayHelp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HighwayHelp.Models;

namespace HighwayHelp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }


   

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Day11/Prashant/HighwayHelp/Controllers/ProductsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HighwayHelp.Models;
using BLL;
using BOL;
using System.Collections.Generic;

namespace HighwayHelp.Controllers;

public class ProductsController : Controller
{
    private readonly ILogger<ProductsController> _logger;

    public ProductsController(ILogger<ProductsController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        HelpManager hm=new HelpManager();
        List<Hospital> allHospitals=hm.GetAllHospitals();
        this.ViewData["hospitals"]=allHospitals;

        return View();
    }

 public IActionResult AllProducts()
    {
        // CatalogManager manager=new CatalogManager();
        // List<Product> allProducts=manager.GetAllProducts();
        // this.ViewData["products"]=allProducts;
        return View();
    }

 public IActionResult ShowAllHospitals()
    {
        HelpManager hm=new HelpManager();
        List<Hospital> allHospitals=hm.GetAllHospitals();
        this.ViewData["hospitals"]=allHospitals;
        
        return View();
    }



    // public IActionResult Details(int id)
    // {
    //     Console.WriteLine("inside controllers Deatils");
    //      HelpManager hm=new HelpManager();
    //      Hospital hospital=hm.GetHospital(id);
    //      this.ViewData["hospital"]=hospital;
    //      return View();

    // } 


    //  public IActionResult Insert(int id, string name, string email, string pin)
    // {
    //    // Console.WriteLine("inside controllers Deatils");
       
    //      HelpManager hm=new HelpManager();
    //      if(hm.InsertHospital(id,name,email,pin))
    //      {
    //     return Redirect("Index");
    //      }
    //     // this.ViewData["hospital"]=hospital;
    //      return View();

    // } 

   

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Day11/Prashant/HighwayHelp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Day11/Prashant/HighwayHelp/Views/Products/AllProducts.cshtml
@using BOL;

@{
    ViewData["Title"] = "Index Page";
}

 <h2>Product Available</h2>

<ol>
    <a href="/Products/ShowAllHospitals"><li>Hospitals</li></a>
    <a><li>Servicing Centers</li></a>
    <a><li>Hotels</li></a>
</ol>

Day11/Prashant/HighwayHelp/Views/Products/Details.cshtml
@using BOL;

@{
    ViewData["Title"] = "Details Page";
}
<h1>@ViewData["Title"]</h1>

@{

Hospital hs=(Hospital)ViewData["hospital"];
<p>@hs.Id</p>
<p>@hs.Name</p>
<p>@hs.Email</p>
<p>@hs.Pin</p>


}

Day11/Prashant/HighwayHelp/Views/Products/ShowAllHospitals.cshtml
@using BOL;
@using System.Collections.Generic;
@{
    ViewData["Title"] = "All Hospitals";
}

<!-- <div class="text-center"> -->
<div>
@{
List<Hospital> allHospitals=(List<Hospital>)ViewData["hospitals"];
    <table cellpadding="10px" border="2px">
@foreach(Hospital h in allHospitals)
{
    @* <ol>
    <p><a href="/Products/Details/@h.Id">@h.Name</a></p>
    </ol> *@

    <tr><td>@h.Id</td><td><a href="/Products/Details/@h.Id">@h.Name</a></td><td>@h.Email</td><td>@h.Pin</td></tr>
    
}
</table>
//Console.WriteLine("inside index");
}
   
</div>

Day11/Prashant/HighwayHelp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HighwayHelp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HighwayHelp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HighwayHelp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HighwayHelp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>